ToChange/Models/Exchange.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ToChange.Models
{
    public class Exchange
    {
        [Key]
        [Required]
        public int ID { get; set; }

        [Required]
        public string FirstCustomerID { get; set; }

        [Required]
        public int FirstProductID { get; set; }

        [Required]
        public string FirstDescription { get; set; }

        [Required]
        public string SecondCustomerID { get; set; }

        [Required]
        public int SecondProductID { get; set; }

        [Required]
        public string SecondDescription { get; set; }
    }
}

ToChange/Controllers/ExchangeController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ToChange.DB_Connections;
using ToChange.Models;
using ToChange.ViewModel;

namespace ToChange.Controllers
{
    public class ExchangeController : Controller
    {

        /// <summary>
        /// Open Poke Popup Window
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult PokeRequest(int id)
        {
            return PartialView(GetProductByID(id));
        }

        /// <summary>
        /// Send a Poke
        /// </summary>
        /// <param name="product"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult PokeRequest(Product product)
        {
            var firstCustomer = websiteSettings.CurrentUser;
            var secondCustomer = GetCustomerByProductID(product.ID);

            

            if (firstCustomer == null || secondCustomer == null || firstCustomer.ID.Equals(secondCustomer.ID))
                return RedirectToAction("NavigateToHomeAction", "Home");


            //Create a Handler Object for swap item 
            SwapHandler swapHandler = new SwapHandler();
            swapHandler.firstCustomerID = firstCustomer.ID;
            swapHandler.secondCustomerID = secondCustomer.ID;
            swapHandler.firstProductID = product.ID;
            swapHandler.secondProductID = 0;

            DAL.Swap.Add(swapHandler);
            DAL.entity.SaveChanges();
            
            //Add To Request Table
            Poke poke = new Poke();
            poke.firstCustomerID = firstCustomer.ID;
            poke.secondCustomerID = secondCustomer.ID;
            poke.ProductID = product.ID;
            poke.AddedOn = DateTime.Now;
            poke.Pending = true;
            poke.RespondAt = websiteSettings.DEFAULT_TIME;
            AddPokeToTable(poke);

            return RedirectToAction("NavigateToHomeAction", "Home");
        }

        /// <summary>
        /// Open Popup window to resend request
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult ReSendPokeRequest(int id)
        {
            return PartialView(GetProductByID(id));
        }

        /// <summary>
        /// Accept the Request And ReSend Request for the customer
        /// </summary>
        /// <param name="product"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult ReSendPokeRequest(Product product)
        {
            var firstCustomer = GetCustomerByProductID(product.ID);
            var secondCustomer = websiteSettings.CurrentUser;


            //for notification
            var request = websiteSettings.GetPokeList(firstCustomer.ID, secondCustomer.ID, websiteSettings.productIDforSwap);

            //for swap process
            var swapRequest = DAL.Swap.Where(a => a.firstCustomerID.Equals(firstCustomer.ID)
            && a.secondCustomerID.Equals(secondCustomer.ID) && a.firstProductID.Equals(websiteSettings.productIDforSwap)).FirstOrDefault();

            if(swapRequest != null)
            {
                if(swapRequest.secondProductID == 0)
                {
                    swapRequest.secondProductID = product.ID;
                    UpdateSwap(swapRequest);
                }
            }

            if(request != null)
            {
                request.RespondAt = DateTime.Now;
                request.ProductIDToSwapWith = product.ID;
                UpdatePoke(request);
            }
            return RedirectToAction("NavigateToHomeAction", "Home");
        }

        /// <summary>
        /// Accept Request
        /// </summary>
        /// <param name="senderID"></param>
        /// <param name="receiverID"></param>
        /// <param name="productID"></param>
        /// <returns></returns>
        public ActionResult AcceptRequest(string senderID, string receiverID , int productID)
        {
            var request = GetPokeList(senderID ,receiverID , productID);

            if(request != null)
            {
                request.Accepted = true;
                request.Pending = false;
                UpdatePoke(request);

                Exchange exchange = new Exchange();
                Product product = DAL.Products.Find(productID);
                Product secondProduct = DAL.Products.Find(request.ProductIDToSwapWith);
                

                exchange.FirstCustomerID = request.firstCustomerID;
                exchange.FirstDescription = product.Description;
                exchange.FirstProductID = productID;
                exchange.SecondCustomerID = receiverID;
                exchange.SecondDescription = secondProduct.Description;
                exchange.SecondProductID = request.ProductIDToSwapWith;

                DAL.Exchanges.Add(exchange);
                DAL.entity.SaveChanges();

                ExchangeProductsBetweenCustomers(request.firstCustomerID, request.secondCustomerID, request.ProductID, request.ProductIDToSwapWith);
            }
            return RedirectToAction("NavigateToHomeAction", "Home");
        }

        /// <summary>
        /// Get Products and Check if they are exist and Update
        /// </summary>
        /// <param name="firstCustomerID"></param>
        /// <param name="secondCustomrID"></param>
        /// <param name="firstProductID"></param>
        /// <param name="secondProductID"></param>
        private void ExchangeProductsBetweenCustomers(string firstCustomerID , string secondCustomrID , int firstProductID , int secondProductID)
        {
            Product firstProduct = GetProductByID(firstProductID);
            Product secondProduct = GetProductByID(secondProductID);

            if (firstProduct != null && secondProduct != null)
            {
                UpdateProductTable(firstProduct, secondCustomrID);
                UpdateProductTable(secondProduct, firstCustomerID);
            }
        }
      
        /// <summary>
        /// Update DataBase
        /// </summary>
        /// <param name="product"></param>
        /// <param name="id"></param>
        private void UpdateProductTable(Product product , string id)
        {

            string ConnectionString = ConfigurationManager.ConnectionStrings["ToChangeDBModelEntities"].ToString();
            string UpdateQuery = "Update Product set CategoryID='" + product.CategoryID +
                "',CustomerID='" + id + "',Description='" +
                 product.Description + "',ProductImage='" + product.ProductImage + "',ProductName='" + product.ProductName + 
                  "' where ID='" + product.ID + "'";
            SqlConnection con = new SqlConnection(ConnectionString);
            SqlCommand cmd = new SqlCommand(UpdateQuery, con);
            if (con.State != System.Data.ConnectionState.Open)
                con.Open();
            cmd.ExecuteNonQuery();

        }

        /// <summary>
        /// Reject Request - Delete from Notification
        /// </summary>
        /// <param name="senderID"></param>
        /// <param name="receiverID"></param>
        /// <param name="productID"></param>
        /// <returns></returns>
        public ActionResult RejectRequest(string senderID, string receiverID, int productID)
        {
            var request = GetPokeList(senderID, receiverID, productID);
            if (request != null)
            {
                request.Accepted = false;
                request.Pending = false;
                UpdatePoke(request);
            }
            return RedirectToAction("NavigateToHomeAction", "Home");
        }

        /// <summary>
        /// Get OpenRequestInfo Page
        /// </summary>
        /// <param name="id"></param>
        /// <param name="requestID"></param>
        /// <returns></returns>
        public ActionResult OpenRequestInfo(int id, string requestID)
        {

            websiteSettings.customerIDforSwap = requestID;
            websiteSettings.productIDforSwap = id;

            return View(GetUserVmModel(id , requestID , 1 , ""));
        }
        
        /// <summary>
        /// Return UserVM Model
        /// </summary>
        /// <param name="id"></param>
        /// <param name="requestID"></param>
        /// <param name="page"></param>
        /// <param name="txtSearch"></param>
        /// <returns></returns>
        private UserVM GetUserVmModel(int id , string requestID , int page , string txtSearch)
        {
            var recieverProduct = GetProductByID(id);
            var senderCustomer = GetCustomerByID(requestID);
            var recieverCustomer = GetCustomerByID(recieverProduct.CustomerID);

            IPagedList<Product> senderProducts;

            if (string.IsNullOrEmpty(txtSearch))
                senderProducts = DAL.Products.Where(a => a.CustomerID.Equals(senderCustomer.ID)).OrderBy(a => a.ProductName)
                    .ToPagedList(page, 7);
            else
                senderProducts = DAL.Products.Where(a => a.CustomerID.Equals(senderCustomer.ID) && a.ProductName.ToLower()
                .Contains(txtSearch.ToLower())).OrderBy(a => a.ProductName).ToPagedList(page, 7);

            UserVM userVM = new UserVM();

            var product = DAL.Swap.Where(a => a.firstCustomerID.Equals(senderCustomer.ID)
            && a.secondCustomerID.Equals(recieverCustomer.ID) && a.firstProductID.Equals(recieverProduct.ID)).FirstOrDefault();
            Product senderProduct = null;

            if (product != null)
            {
               senderProduct = GetProductByID(product.secondProductID);
            }
            
            userVM.senderCustomer = senderCustomer;
            userVM.recieverProduct = recieverProduct;
            userVM.Products = senderProducts;
            userVM.recieverCustomer = recieverCustomer;

ToChange/Views/Exchange/OpenRequestInfo.cshtml
@model ToChange.ViewModel.UserVM
@using ToChange.Models
@using PagedList
@using PagedList.Mvc


@{
    ViewBag.Title = Model.recieverProduct.ProductName + " Swap Request";
}


<br />

<!-- Sender -->

@if (websiteSettings.CurrentUser.ID.Equals(Model.senderCustomer.ID))
{

    <div>
        @{
            var sentence = "";
            sentence = Model.recieverCustomer.FirstName + " accepted your request and send you Swap request for " + Model.senderProduct.ProductName;
        }
        <h4>@sentence</h4>
        <hr />
        <div class="form-horizontal">
            @Html.HiddenFor(model => model.senderProduct.ID)

            <div class="form-group">
                <img style="margin-left:10%;" src="@Model.senderProduct.ProductImage" width="350" height="200" />
            </div>

            <br />

            <div class="form-group">
                @Html.LabelFor(model => model.senderProduct.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.senderProduct.ProductName, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", disabled = true } })
                    @Html.ValidationMessageFor(model => model.senderProduct.ProductName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.senderProduct.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input class="form-control" type="text" disabled="disabled" value="@websiteSettings.GetCategoryName(Model.senderProduct.CategoryID)" />
                    @Html.ValidationMessageFor(model => model.senderProduct.CategoryID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.senderProduct.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.senderProduct.Description, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", disabled = true } })
                    @Html.ValidationMessageFor(model => model.senderProduct.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @if (Model.recieverProduct != null && Model.senderProduct != null)
                    {
                        <input class="btn btn-success" style="width:125px;" value="Accept" onclick="location.href='@Url.Action("AcceptRequest", "Exchange", new { senderID = Model.senderCustomer.ID, receiverID = Model.recieverCustomer.ID, productID = Model.recieverProduct.ID })'" />
                    }
                    <input class="btn btn-danger" value="Reject" style="width:125px;" onclick="location.href='@Url.Action("RejectRequest", "Exchange", new { senderID = Model.senderCustomer.ID, receiverID = Model.recieverCustomer.ID, productID = Model.recieverProduct.ID })'" />
                </div>
            </div>
        </div>
        <br />

    </div>

            }

<!-- Reciever -->

@if (!websiteSettings.CurrentUser.ID.Equals(Model.senderCustomer.ID))
{
    var sentence = "";
    sentence = "Swap Request for " + Model.recieverProduct.ProductName + " from " + Model.senderCustomer.FirstName;
    <div>

        <h4>@sentence</h4>
        <hr />
        <div class="form-horizontal">
            @Html.HiddenFor(model => model.recieverProduct.ID)

            <div class="form-group">
                <img style="margin-left:10%;" src="@Model.recieverProduct.ProductImage" width="350" height="200" />
            </div>

            <br />

            <div class="form-group">
                @Html.LabelFor(model => model.recieverProduct.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.recieverProduct.ProductName, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", disabled = true } })
                    @Html.ValidationMessageFor(model => model.recieverProduct.ProductName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.recieverProduct.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input class="form-control" type="text" disabled="disabled" value="@websiteSettings.GetCategoryName(Model.recieverProduct.CategoryID)" />
                    @Html.ValidationMessageFor(model => model.recieverProduct.CategoryID, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.recieverProduct.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.recieverProduct.Description, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", disabled = true } })
                    @Html.ValidationMessageFor(model => model.recieverProduct.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @if (Model.senderProduct != null && Model.recieverProduct != null)
                {
                        <input class="btn btn-success" style="width:125px;" value="Accept" onclick="location.href='@Url.Action("AcceptRequest", "Exchange", new { senderID = Model.senderCustomer.ID, receiverID = Model.recieverCustomer.ID, productID = Model.recieverProduct.ID })'" />
                    }
                    <input class="btn btn-danger" value="Reject" style="width:125px;" onclick="location.href='@Url.Action("RejectRequest", "Exchange", new { senderID = Model.senderCustomer.ID, receiverID = Model.recieverCustomer.ID, productID = Model.recieverProduct.ID })'" />
                </div>
            </div>
        </div>

    </div>

}
<br />



<!-- Table Of Sender Products-->

@if (!websiteSettings.CurrentUser.ID.Equals(Model.senderCustomer.ID))
{
    <h3>You Can Choose One Of @Model.senderCustomer.FirstName products to swap with or cancel the request</h3>
    <br />


            <div>
                @using (Html.BeginForm("SearchProduct", "Exchange", FormMethod.Get))
                {
                    <div class="panel panel-primary" style="width:100%">
                        <div class="panel-heading clearfix">

                            <h4 class="panel-title pull-left" style="font-size:30px; font-style:oblique;"><span class="glyphicon glyphicon-star"></span>@Model.senderCustomer.FirstName Products</h4>
                            <div class="input-group">
                                @Html.TextBox("txtSearch", "", htmlAttributes: new
               {
                   @type = "search",
                   @class = "form-control shortInputSearch pull-right",
                   @autocomplete = "off",
                   @placeholder = "Filter, search items.."
               })
                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-primary"><i class="glyphicon glyphicon-search"></i></button>
                                    <button onclick="Clear()" class="btn btn-primary"><i class="glyphicon glyphicon-remove-sign"></i></button>
                                    <button onclick="location.href='@Url.Action("SearchProduct", "Exchange")'" type="button" class="btn btn-primary"><i class="glyphicon glyphicon-refresh"></i></button>

                                </div>
                            </div>
                        </div>

                        <table class="table table-striped table-hover table-responsive  table-condensed" style="width:100%">
                            <tr>
                                <th>
                                    <h3 style="font-size:x-large"><span style="font-weight:bolder">Product</span></h3>
                                </th>
                                <th>
                                    <h3 style="font-size:x-large"><span style="font-weight:bolder">Category</span></h3>
                                </th>

                                <th>
                                    <h3 style="font-size:x-large"><span style="font-weight:bolder">Description</span></h3>
                                </th>
                                <th>
                                    <h3 style="font-size:x-large"><span style="font-weight:bolder">senderCustomer ID</span></h3>
                                </th>

                                <th> </th>
                            </tr>
                            @if (Model.Products != null && Model.Products.Count() > 0)
                            {
                                foreach (var item in Model.Products)
                                {
                                    <tr>
                                        <td class="col-lg-1">
                                            <span style="font-size: 17px;">@Html.DisplayFor(modelItem => item.ProductName)</span>
                                        </td>
                                        <td class="col-lg-1">
                                            <span style="font-size: 17px;">@websiteSettings.GetCategoryName(item.CategoryID)</span>
                                        </td>

                                        <td class="col-lg-1">
                                            <span style="font-size: 17px;">@Html.DisplayFor(modelItem => item.Description)</span>
                                        </td>
                                        <td class="col-lg-1" style="text-align:center;">
                                            <span style="font-size: 17px;">@Html.DisplayFor(modelItem => item.CustomerID)</span>
                                        </td>


                                        <td class="col-lg-3">
                                            <button type="button" class="btn btn-info col-lg-3 col-lg-offset-1" onclick="OpenPopup(@websiteSettings.VIEW_SINGLE_IMAGE , @item.ID)"><span style="margin-right: 5px" class="glyphicon glyphicon-align-justify"></span>Details</button>
                                            <button type="button" class="btn btn-primary col-lg-3 col-lg-offset-1" onclick="OpenPopup(@websiteSettings.RE_SEND_POKE_REQUEST , @item.ID)"><span style="margin-right: 5px" class="glyphicon glyphicon-refresh"></span>Request</button>
                                        </td>
                                    </tr>
                                }
                            }
                        </table>
                    </div>

                    <div style="text-align:center;">
                        @Html.PagedListPager(Model.Products, page => Url.Action("Pagination", new { page }), new PagedListRenderOptions() { Display = PagedListDisplayMode.IfNeeded })
                    </div>
                }
            </div>

}
<script>


    function Clear() {
        $('#txtSearch').val("");
    }

</script>

ToChange/Views/Exchange/PokeRequest.cshtml
@using ToChange.Models
@model ToChange.Models.Product

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="panel panel-primary">
        <div class="panel-heading">
            @if (Model != null)
            {
                <h4 style="text-align:center;">Are you sure you want to send Swap request?</h4>
            }
        </div>
        <div class="panel-body">
            @Html.HiddenFor(model => model.ID)

            <fieldset id="formData">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)

                    <div class="form-group">
                        <img style="margin-left:10%;" src="@Model.ProductImage" width="350" height="200" />
                    </div>

                    <br />

                    <div class="form-group">
                        @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", disabled = true } })
                            @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input class="form-control" type="text" disabled="disabled" value="@websiteSettings.GetCategoryName(Model.CategoryID)" />
                            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", disabled = true } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="button" onclick="Submit()" value="Send Now!" class="btn btn-success" />
                            <input type="button" onclick="Cancel()" value="Close" class="btn btn-danger" />
                        </div>
                    </div>
                </div>

            </fieldset>
        </div>
    </div>

}


<script>

    function Submit() {

        $.ajax({
            type: 'POST',
            url: '/Exchange/PokeRequest',
            data: $('#formData').serialize(),
            success: function () {
                alert('Poke Sent');
                location.reload();
            }
            
        });

    }

    function Cancel() {
        location.reload();
    }

</script>

ToChange/Views/Exchange/ReSendPokeRequest.cshtml
@using ToChange.Models
@model ToChange.Models.Product

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="panel panel-primary">
        <div class="panel-heading">
            @if (Model != null)
            {
                <h4 style="text-align:center;">Are you sure you want to send Swap request?</h4>
            }
        </div>
        <div class="panel-body">
            @Html.HiddenFor(model => model.ID)

            <fieldset id="formData">
                <div class="form-horizontal">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)

                    <div class="form-group">
                        <img style="margin-left:10%;" src="@Model.ProductImage" width="350" height="200" />
                    </div>

                    <br />

                    <div class="form-group">
                        @Html.LabelFor(model => model.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.ProductName, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", disabled = true } })
                            @Html.ValidationMessageFor(model => model.ProductName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.CategoryID, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <input class="form-control" type="text" disabled="disabled" value="@websiteSettings.GetCategoryName(Model.CategoryID)" />
                            @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control", autocomplete = "off", disabled = true } })
                            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="button" onclick="Submit()" value="Send Now!" class="btn btn-success" />
                            <input type="button" onclick="Cancel()" value="Close" class="btn btn-danger" />
                        </div>
                    </div>
                </div>

            </fieldset>
        </div>
    </div>

}


<script>

    function Submit() {

        $.ajax({
            type: 'POST',
            url: '/Exchange/ReSendPokeRequest',
            data: $('#formData').serialize(),
            success: function () {
                location.reload();
            }

        });

    }

    function Cancel() {
        location.reload();
    }

</script>